import 'bootstrap/dist/css/bootstrap.min.css'
import '@/app/_styles/globals.scss'
// 導入
import Navbar from './_components/navbar'
import Footer from './_components/footer'

export const metadata = {
  title: 'Bark & Bijou',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ height: '100%' }}>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
